// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://arkwwtpdaatnwyhwfvmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFya3d3dHBkYWF0bnd5aHdmdm11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyNTAyOTAsImV4cCI6MjA4OTgyNjI5MH0.r3lM9qlDVjss4q6xYI-j9HdDD6QcOzAQB3vlSxMy8MM";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);