// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yyzokpnlxtikijmfggro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5em9rcG5seHRpa2lqbWZnZ3JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyNTQ0OTQsImV4cCI6MjA4OTgzMDQ5NH0.EikaPPB0ZjRZX67z2rbXVw0Stn81op2XZVnOSNb-CNY";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);